language: python
python:
  - "3.5"
dist: xenial
sudo: required
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install python-dev libhdf5-serial-dev
install:
  - pip install scipy pandas h5py requests Pillow rectpack scikit-image pysmb
script:
  - python -m unittest discover
branches:
  only:
    - master
