[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pyifcb"
version = "1.1.1"
description = "Imaging FlowCytobot Python API, generation 2"
readme = "README.md"
authors = [{name = "Joe Futrelle", email = "jfutrelle@whoi.edu"}]
classifiers = [
    'Development Status :: 3 - Alpha',
    'Intended Audience :: Developers',
    'Intended Audience :: Science/Research',
    'License :: OSI Approved :: MIT License',
    'Operating System :: POSIX :: Linux',
    'Programming Language :: Python',
    'Topic :: Scientific/Engineering',
]
keywords = ['FlowCytobot','Imaging','ifcb']

[tool.hatch.build.targets.wheel]
include = [
    "ifcb/**/*",
    "docs/**/*",
    "auto_transfer.py",
    "VERSION",
    "LICENSE",
    "README.md",
    "transfer_config.yml.example",
]

dependencies = [
    "scipy==1.12.0",
    "pandas==2.2.1",
    "h5py==3.10.0",
    "requests==2.32.0",
    "Pillow==10.3.0",
    "rectpack==0.2.2",
    "scikit-image==0.22.0",
    "pysmb==1.2.9.1",
    "smbprotocol==1.13.0",
    "pyyaml==6.0.1"
]

[project.scripts]
auto_transfer = "auto_transfer:main"

[tool.hatch.metadata]
allow-direct-references = true

[project.urls]
Repository = "https://github.com/joefutrelle/pyifcb"
Documentation = "https://github.com/joefutrelle/pyifcb/wiki"
Issues = "https://github.com/joefutrelle/pyifcb/issues"